theme: jekyll-theme-cayman
show_downloads: true
github:
  version.115: http://google.com/5
  version.114: http://google.com/4
  version.113: http://google.com/3
  version.112: http://google.com/2
  version.19: http://google.com/1
  version.18: http://google.com/8
