name: SellStick
main: com.acropolismc.play.sellstick.SellStick
version: 8.0.9.0
author: shmkane
website: http://acropolismc.com
depend: [Vault, Essentials]
softdepend: [Factions, Essentials, MassiveCore, LegacyFactions, ASkyBlock, PlotSquared]
commands:
   sellstick:
      description: Sell all items in a chest easily!
