name: SellStick
main: com.shmkane.sellstick.SellStick
version: 1.16.4v2
api-version: 1.16
author: shmkane
website: https://github.com/shmkane/SellStick
depend: [Vault]
softdepend: [Essentials, ShopGuiPlus]
commands:
  sellstick:
    description: Sell all items in a chest easily!
