name: SellStick
main: com.shmkane.sellstick.SellStick
version: 1.9.4
#api-version: DNE BEFORE 1.13
author: shmkane
website: https://github.com/shmkane/SellStick
depend: [Vault]
softdepend: [Essentials, ShopGuiPlus]
commands:
  sellstick:
    description: Sell all items in a chest easily!
